// packages/react/src/components/nodes/EndNode.tsx
/**
 * 结束节点组件
 */

import React, { memo } from 'react';
import { Handle, Position, NodeProps } from 'reactflow';

interface EndNodeData {
  title: string;
  description?: string;
}

export const EndNode = memo<NodeProps<EndNodeData>>(({ data, selected }) => {
  return (
    <div
      style={{
        padding: '12px 20px',
        borderRadius: 8,
        background: 'linear-gradient(135deg, #f093fb 0%, #f5576c 100%)',
        color: '#fff',
        border: selected ? '2px solid #1890ff' : '2px solid transparent',
        boxShadow: selected
          ? '0 4px 12px rgba(24, 144, 255, 0.4)'
          : '0 2px 8px rgba(0, 0, 0, 0.15)',
        minWidth: 180,
        cursor: 'pointer',
        transition: 'all 0.3s ease'
      }}
    >
      <Handle
        type="target"
        position={Position.Left}
        style={{
          background: '#fff',
          width: 10,
          height: 10,
          border: '2px solid #f5576c'
        }}
      />

      <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
        <span style={{ fontSize: 20 }}>🏁</span>
        <div>
          <div style={{ fontWeight: 600, fontSize: 14 }}>{data.title || '结束'}</div>
          {data.description && (
            <div style={{ fontSize: 12, opacity: 0.9, marginTop: 4 }}>
              {data.description}
            </div>
          )}
        </div>
      </div>
    </div>
  );
});

EndNode.displayName = 'EndNode';

// packages/vue/src/components/nodes/EndNode.vue
<template>
  <div class="flow-node flow-node-end" :style="nodeStyle">
    <Handle type="target" :position="Position.Top" />
    <div class="node-icon">🏁</div>
    <div class="node-content">
      <div class="node-title">{{ data.title || '结束' }}</div>
      <div v-if="data.description" class="node-description">
        {{ data.description }}
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue';
import { Handle, Position } from '@vue-flow/core';

interface Props {
  data: {
    title?: string;
    description?: string;
    [key: string]: any;
  };
}

const props = defineProps<Props>();

const nodeStyle = computed(() => ({
  background: 'linear-gradient(135deg, #f5576c 0%, #f093fb 100%)',
  color: '#fff',
  padding: '12px 16px',
  borderRadius: '8px',
  minWidth: '160px',
  boxShadow: '0 4px 12px rgba(245, 87, 108, 0.3)',
  border: '2px solid #f5576c'
}));
</script>

<style scoped>
.flow-node {
  display: flex;
  align-items: center;
  gap: 12px;
  cursor: pointer;
  transition: all 0.3s;
}

.flow-node:hover {
  transform: translateY(-2px);
  box-shadow: 0 6px 16px rgba(0, 0, 0, 0.2) !important;
}

.node-icon {
  font-size: 24px;
  line-height: 1;
}

.node-content {
  flex: 1;
}

.node-title {
  font-weight: 600;
  font-size: 14px;
  margin-bottom: 4px;
}

.node-description {
  font-size: 12px;
  opacity: 0.9;
  line-height: 1.4;
}
</style>
