// packages/react/src/components/nodes/StartNode.tsx
/**
 * 开始节点组件
 */

import React, { memo } from 'react';
import { Handle, Position, NodeProps } from 'reactflow';

interface StartNodeData {
  title: string;
  description?: string;
}

export const StartNode = memo<NodeProps<StartNodeData>>(({ data, selected }) => {
  return (
    <div
      style={{
        padding: '12px 20px',
        borderRadius: 8,
        background: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
        color: '#fff',
        border: selected ? '2px solid #1890ff' : '2px solid transparent',
        boxShadow: selected
          ? '0 4px 12px rgba(24, 144, 255, 0.4)'
          : '0 2px 8px rgba(0, 0, 0, 0.15)',
        minWidth: 180,
        cursor: 'pointer',
        transition: 'all 0.3s ease'
      }}
    >
      <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
        <span style={{ fontSize: 20 }}>▶️</span>
        <div>
          <div style={{ fontWeight: 600, fontSize: 14 }}>{data.title || '开始'}</div>
          {data.description && (
            <div style={{ fontSize: 12, opacity: 0.9, marginTop: 4 }}>
              {data.description}
            </div>
          )}
        </div>
      </div>

      <Handle
        type="source"
        position={Position.Right}
        style={{
          background: '#fff',
          width: 10,
          height: 10,
          border: '2px solid #667eea'
        }}
      />
    </div>
  );
});

StartNode.displayName = 'StartNode';

// packages/vue/src/components/nodes/StartNode.vue
<template>
  <div class="flow-node flow-node-start" :style="nodeStyle">
    <div class="node-icon">🚀</div>
    <div class="node-content">
      <div class="node-title">{{ data.title || '开始' }}</div>
      <div v-if="data.description" class="node-description">
        {{ data.description }}
      </div>
    </div>
    <Handle type="source" :position="Position.Bottom" />
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue';
import { Handle, Position } from '@vue-flow/core';

interface Props {
  data: {
    title?: string;
    description?: string;
    [key: string]: any;
  };
}

const props = defineProps<Props>();

const nodeStyle = computed(() => ({
  background: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
  color: '#fff',
  padding: '12px 16px',
  borderRadius: '8px',
  minWidth: '160px',
  boxShadow: '0 4px 12px rgba(102, 126, 234, 0.3)',
  border: '2px solid #667eea'
}));
</script>

<style scoped>
.flow-node {
  display: flex;
  align-items: center;
  gap: 12px;
  cursor: pointer;
  transition: all 0.3s;
}

.flow-node:hover {
  transform: translateY(-2px);
  box-shadow: 0 6px 16px rgba(0, 0, 0, 0.2) !important;
}

.node-icon {
  font-size: 24px;
  line-height: 1;
}

.node-content {
  flex: 1;
}

.node-title {
  font-weight: 600;
  font-size: 14px;
  margin-bottom: 4px;
}

.node-description {
  font-size: 12px;
  opacity: 0.9;
  line-height: 1.4;
}
</style>
